### PR TITLE
Update Radarr to First release of 3.0 series builds

### PR DESCRIPTION
**Pull request by coder8338**
Update Radarr to First release of 3.0 series builds added dotnet-runtime-3.1 install to script.

### CODE REVIEW

**Comment by coder8338** [comment]
Thanks for this @Toetje585

**Comment by Toetje585** [comment]
Please note that nginx seems to reroute http to https that will cause radarr to fail download from Jacket,  

#proxy_set_header X-Forwarded-Host $http_host:443;
#proxy_set_header X-Forwarded-Port 443;
#proxy_set_header X-Forwarded-Proto https;

Not sure if we need to disable all of them I didn't use nginx for quite some time but this solved my download issue in radarr for now:

`Connection refused Connection refused: 'https://vnc.*.appboxes.co/jackett/dl/iptorrents/?jackett_apikey=(removed)&path=*
`

**Comment by coder8338** [comment]
@Toetje585 I've tried to update the code to handle this, can you please delete all your proxy header code from `/etc/nginx/sites-enabled/default` and try this command:

```
sed -i '/^server {/i \
map $http_host $port {\
        default 80;\
        "~^[^\:]+:(?<p>\d+)$" $p;\
}\
' /etc/nginx/sites-enabled/default
sed -i '/server_name _/a \
        proxy_set_header X-Real-IP $remote_addr;\
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;\
        proxy_set_header X-Forwarded-Server $host;\
        proxy_set_header X-Forwarded-Port $port;\
        proxy_set_header X-Forwarded-Proto $scheme;\
        proxy_http_version 1.1;\
        proxy_set_header Upgrade $http_upgrade;\
        proxy_set_header Connection $http_connection;\
        proxy_set_header Host $host;\
        proxy_cache_bypass $http_upgrade;\
        proxy_set_header X-Forwarded-Host $host;\
        proxy_connect_timeout 300s;\
        proxy_read_timeout 300s;\
        client_header_timeout 300s;\
        client_body_timeout 300s;\
        client_max_body_size 1000M;\
        send_timeout 300s;' /etc/nginx/sites-enabled/default
```

After that reload nginx using `pkill -HUP nginx`. Let me know if it works, I've tried to use variables for the ports so it can be used externally and internally.

**Comment by Toetje585** [comment]
Hello,

Thank you for looking into it, yes this seem to fixed it.

Best Regards,

**Pull request merged**
